# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "oracle-5.8-i386.virtualbox"
  
  config.vm.box_check_update = false
  
  config.vm.network "forwarded_port", guest: 7777, host: 7777
  
  #config.vm.network "private_network", ip: "192.168.33.10"
  
  #config.vm.network "public_network"
  
  config.vm.synced_folder "../../vagrant-software", "/vagrant-software"
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = "true"
	vb.customize  ["modifyvm",
                  :id, 
                  "--cpus", "1",
                  "--memory", "2048",
                  "--vram", "32"]
  end
  
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  config.vm.provision :shell, path: "scripts/bootstrap.sh"

  config.vm.provision :shell, path: "scripts/oas-pre-install.sh"

end
