# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

	config.vm.define "apache-box-catalogue" do |abc|
    
		abc.vm.box = "oracle-5.8-i386.virtualbox"
  
		abc.vm.box_check_update = false
  
		abc.vm.network "forwarded_port", guest: 80, host: 4444
  
		#abc.vm.network "private_network", ip: "192.168.33.10"
  
		#abc.vm.network "public_network"
  
		abc.vm.synced_folder "../../travcorp-bento/builds", "/vagrant-boxes"
  
		abc.vm.provider "virtualbox" do |vb|
			vb.gui = "true"
			vb.customize  ["modifyvm",
				:id, 
                "--cpus", "1",
                "--memory", "1024",
                "--vram", "32"]
		end
  
		abc.vm.provision :shell, path: "scripts/bootstrap.sh"
		
	end

end