# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "oracle-db-not-installed.virtualbox"
  
  config.vm.box_check_update = true
  
  config.vm.network "forwarded_port", guest: 1521, host: 1521
  
  #config.vm.network "private_network", ip: "192.168.33.10"
  
  #config.vm.network "public_network"
  
  config.vm.synced_folder "../../travcorp-bento/software/oracle-db", "/home/oracle/oracle-db"
  
  config.vm.provider "virtualbox" do |vb|
    vb.customize  ["modifyvm",
                  :id, 
                  "--cpus", "1",
                  "--memory", "2048",
                  "--vram", "32"]
  end
  
  #config.vm.provision :shell, path: "scripts/bootstrap.sh"

end