# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'getoptlong'

opts = GetoptLong.new(
	[ '--version', GetoptLong::OPTIONAL_ARGUMENT ]
)
version='dev'
opts.each do |opt, arg|
	case opt
		when '--version'
		version=arg
	end
end
Vagrant.configure(2) do |config|
	config.vm.define "tropics-db", autostart: false do |trps|
		trps.vm.box = "travcorp/oracle-db"
		trps.vm.network "forwarded_port", guest: 1521, host: 1521
		trps.vm.provision "shell" do |s|
			s.path = "scripts/provision.sh" 
			s.args = "#{version}"
		end
	end
	config.vm.define "tmg-db", autostart: false do |tmg|
		#tmg.vm.box = "travcorp/oracle-db"
		#tmg.vm.network "forwarded_port", guest: 1521, host: 1521
		#TODO
	end
	config.vm.define "ch2-db", autostart: false do |ch2|
		#ch2.vm.box = "travcorp/oracle-db"
		#ch2.vm.network "forwarded_port", guest: 1521, host: 1521
		#TODO
	end
end
